FROM python:3.12-slim

WORKDIR /app


RUN apt update && \
    apt install -y libopencv-dev && \
    apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

COPY ../ .

RUN pip3 install -r requirements.txt
